### ISSUE TITLE
Baum\Providers\BaumServiceProvider not found

### ISSUE THREAD

**Issue by namemsile** [DraperStudio/Laravel-Commentable#1]
composer require "baum/baum": "~1.1" 
Missed dependency in composer.json?

**Comment by DraperStudio** [comment]
Tagged v1.0.2. I Forgot to remove the Service Provider after switching to another nested-set package.

**Comment by namemsile** [comment]
Works!

**Comment by namemsile** [comment]
Hm.. how update or delete comment?
something like:
```
$comments = $post->comments() // Collection

$comment->save();
$comment->delete();
```

**Comment by DraperStudio** [comment]
You should be able to just do the following.

```
$post->comments()->find(1)->update(['title' => 'new title', 'body' => 'new body']);
$post->comments()->find(1)->delete();
```

I might add some methods to make that shorter during the weekend so you could do it that way.

```
$post->updateCommentById(1, ['title' => 'new title', 'body' => 'new body']);
$post->deleteCommentById(1);
```

**Comment by DraperStudio** [comment]
Tagged v1.0.4 which now contains the updateComment and deleteComment methods.

Check the README on how to use them.

**Comment by namemsile** [comment]
So quickly!
I just had forked repo for creating those methods, but too late :)

Many thanks.
