### ISSUE TITLE
Feature REquest

### ISSUE THREAD

**Issue by maximusblade** [DraperStudio/Laravel-Commentable#1]
Nice to have:

- Delete all comments per model
- List all comments ( filter by * [date, user ,created_at attribute ])
- adding extra (or dynamic ) comment attributes (eg, approved, visibility, comment_type, no_reply etc )

**Comment by DraperStudio** [comment]
The `comments` method returns a `morphMany` relationship so you can just call any Eloquent methods on those. This way you can delete and filter the comments however you want.

Might add the meta attributes one day, but not for now.
