### ISSUE TITLE
Composer CommentableServiceProvider not found

### ISSUE THREAD

**Issue by Spoowy** [DraperStudio/Laravel-Commentable#2]
I'm getting this error since today when trying to composer update:
```
php artisan clear-compiled

  [Symfony\Component\Debug\Exception\FatalErrorException]                
  Class 'DraperStudio\Commentable\CommentableServiceProvider' not found 
```

**Comment by DraperStudio** [comment]
Check the README, I've moved around a few things and tagged v1.1.0.

You should use ~1.0 or ~1.1, seems like you have used ^1.0 or >=1.0 and received an update which you shouldn't have received without breaking changes.

**Comment by Spoowy** [comment]
Sorry, I've been trying both versions now but the same error is persisting.

**Comment by DraperStudio** [comment]
Check the README, you need to change the name of the ServiceProvider.

**Comment by Spoowy** [comment]
Changed
'DraperStudio\Commentable\CommentableServiceProvider'
to
'DraperStudio\Commentable\ServiceProvider::class'
Reinstalled the package(according to README), still, the same error appears when updating. What am I missing?

**Comment by DraperStudio** [comment]
`DraperStudio\Commentable\ServiceProvider::class` not `'DraperStudio\Commentable\ServiceProvider::class'`

**Comment by Spoowy** [comment]
Perfect, worked fine. Many thanks!
